name: easy_puzzle_game
description: This is a slide puzzle game. Give your image and it make puzzle for you.
version: 0.0.2
repository: https://github.com/nooralibutt/easy_puzzle_game
homepage: https://github.com/nooralibutt/easy_puzzle_game

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.1
  confetti: ^0.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  just_audio: ^0.9.31
  fake_async: ^1.3.1
  gap: ^2.0.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.10
  collection: ^1.17.0
  cached_network_image: ^3.2.3
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: